/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppTasksRouteImport } from './routes/_app.tasks'
import { Route as AppTaskAddRouteImport } from './routes/_app.task-add'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppReportsRouteImport } from './routes/_app.reports'
import { Route as AppRecruitmentRouteImport } from './routes/_app.recruitment'
import { Route as AppProjectsRouteImport } from './routes/_app.projects'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppPerformanceRouteImport } from './routes/_app.performance'
import { Route as AppPayrollRouteImport } from './routes/_app.payroll'
import { Route as AppNotificationsRouteImport } from './routes/_app.notifications'
import { Route as AppMessagesRouteImport } from './routes/_app.messages'
import { Route as AppMeetingsRouteImport } from './routes/_app.meetings'
import { Route as AppLeaveRouteImport } from './routes/_app.leave'
import { Route as AppExpensesRouteImport } from './routes/_app.expenses'
import { Route as AppEmployeesRouteImport } from './routes/_app.employees'
import { Route as AppEmployeeAddRouteImport } from './routes/_app.employee-add'
import { Route as AppDocumentsRouteImport } from './routes/_app.documents'
import { Route as AppDepartmentsRouteImport } from './routes/_app.departments'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppAttendanceRouteImport } from './routes/_app.attendance'
import { Route as AppLiveTasksRouteImport } from './routes/_app.live.tasks'
import { Route as AppLiveMeetingsRouteImport } from './routes/_app.live.meetings'
import { Route as AppLiveDirectoryRouteImport } from './routes/_app.live.directory'
import { Route as AppEmployeesIdRouteImport } from './routes/_app.employees.$id'
import { Route as AppLiveTasksIndexRouteImport } from './routes/_app.live.tasks.index'
import { Route as AppLiveTasksTaskIdRouteImport } from './routes/_app.live.tasks.$taskId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppTasksRoute = AppTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AppRoute,
} as any)
const AppTaskAddRoute = AppTaskAddRouteImport.update({
  id: '/task-add',
  path: '/task-add',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppRecruitmentRoute = AppRecruitmentRouteImport.update({
  id: '/recruitment',
  path: '/recruitment',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsRoute = AppProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppPerformanceRoute = AppPerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => AppRoute,
} as any)
const AppPayrollRoute = AppPayrollRouteImport.update({
  id: '/payroll',
  path: '/payroll',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppMessagesRoute = AppMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AppRoute,
} as any)
const AppMeetingsRoute = AppMeetingsRouteImport.update({
  id: '/meetings',
  path: '/meetings',
  getParentRoute: () => AppRoute,
} as any)
const AppLeaveRoute = AppLeaveRouteImport.update({
  id: '/leave',
  path: '/leave',
  getParentRoute: () => AppRoute,
} as any)
const AppExpensesRoute = AppExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => AppRoute,
} as any)
const AppEmployeesRoute = AppEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => AppRoute,
} as any)
const AppEmployeeAddRoute = AppEmployeeAddRouteImport.update({
  id: '/employee-add',
  path: '/employee-add',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentsRoute = AppDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AppRoute,
} as any)
const AppDepartmentsRoute = AppDepartmentsRouteImport.update({
  id: '/departments',
  path: '/departments',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAttendanceRoute = AppAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AppRoute,
} as any)
const AppLiveTasksRoute = AppLiveTasksRouteImport.update({
  id: '/live/tasks',
  path: '/live/tasks',
  getParentRoute: () => AppRoute,
} as any)
const AppLiveMeetingsRoute = AppLiveMeetingsRouteImport.update({
  id: '/live/meetings',
  path: '/live/meetings',
  getParentRoute: () => AppRoute,
} as any)
const AppLiveDirectoryRoute = AppLiveDirectoryRouteImport.update({
  id: '/live/directory',
  path: '/live/directory',
  getParentRoute: () => AppRoute,
} as any)
const AppEmployeesIdRoute = AppEmployeesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppEmployeesRoute,
} as any)
const AppLiveTasksIndexRoute = AppLiveTasksIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppLiveTasksRoute,
} as any)
const AppLiveTasksTaskIdRoute = AppLiveTasksTaskIdRouteImport.update({
  id: '/$taskId',
  path: '/$taskId',
  getParentRoute: () => AppLiveTasksRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/auth': typeof AuthRoute
  '/attendance': typeof AppAttendanceRoute
  '/dashboard': typeof AppDashboardRoute
  '/departments': typeof AppDepartmentsRoute
  '/documents': typeof AppDocumentsRoute
  '/employee-add': typeof AppEmployeeAddRoute
  '/employees': typeof AppEmployeesRouteWithChildren
  '/expenses': typeof AppExpensesRoute
  '/leave': typeof AppLeaveRoute
  '/meetings': typeof AppMeetingsRoute
  '/messages': typeof AppMessagesRoute
  '/notifications': typeof AppNotificationsRoute
  '/payroll': typeof AppPayrollRoute
  '/performance': typeof AppPerformanceRoute
  '/profile': typeof AppProfileRoute
  '/projects': typeof AppProjectsRoute
  '/recruitment': typeof AppRecruitmentRoute
  '/reports': typeof AppReportsRoute
  '/settings': typeof AppSettingsRoute
  '/task-add': typeof AppTaskAddRoute
  '/tasks': typeof AppTasksRoute
  '/employees/$id': typeof AppEmployeesIdRoute
  '/live/directory': typeof AppLiveDirectoryRoute
  '/live/meetings': typeof AppLiveMeetingsRoute
  '/live/tasks': typeof AppLiveTasksRouteWithChildren
  '/live/tasks/$taskId': typeof AppLiveTasksTaskIdRoute
  '/live/tasks/': typeof AppLiveTasksIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/attendance': typeof AppAttendanceRoute
  '/dashboard': typeof AppDashboardRoute
  '/departments': typeof AppDepartmentsRoute
  '/documents': typeof AppDocumentsRoute
  '/employee-add': typeof AppEmployeeAddRoute
  '/employees': typeof AppEmployeesRouteWithChildren
  '/expenses': typeof AppExpensesRoute
  '/leave': typeof AppLeaveRoute
  '/meetings': typeof AppMeetingsRoute
  '/messages': typeof AppMessagesRoute
  '/notifications': typeof AppNotificationsRoute
  '/payroll': typeof AppPayrollRoute
  '/performance': typeof AppPerformanceRoute
  '/profile': typeof AppProfileRoute
  '/projects': typeof AppProjectsRoute
  '/recruitment': typeof AppRecruitmentRoute
  '/reports': typeof AppReportsRoute
  '/settings': typeof AppSettingsRoute
  '/task-add': typeof AppTaskAddRoute
  '/tasks': typeof AppTasksRoute
  '/': typeof AppIndexRoute
  '/employees/$id': typeof AppEmployeesIdRoute
  '/live/directory': typeof AppLiveDirectoryRoute
  '/live/meetings': typeof AppLiveMeetingsRoute
  '/live/tasks/$taskId': typeof AppLiveTasksTaskIdRoute
  '/live/tasks': typeof AppLiveTasksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/_app/attendance': typeof AppAttendanceRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/departments': typeof AppDepartmentsRoute
  '/_app/documents': typeof AppDocumentsRoute
  '/_app/employee-add': typeof AppEmployeeAddRoute
  '/_app/employees': typeof AppEmployeesRouteWithChildren
  '/_app/expenses': typeof AppExpensesRoute
  '/_app/leave': typeof AppLeaveRoute
  '/_app/meetings': typeof AppMeetingsRoute
  '/_app/messages': typeof AppMessagesRoute
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/payroll': typeof AppPayrollRoute
  '/_app/performance': typeof AppPerformanceRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/projects': typeof AppProjectsRoute
  '/_app/recruitment': typeof AppRecruitmentRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/task-add': typeof AppTaskAddRoute
  '/_app/tasks': typeof AppTasksRoute
  '/_app/': typeof AppIndexRoute
  '/_app/employees/$id': typeof AppEmployeesIdRoute
  '/_app/live/directory': typeof AppLiveDirectoryRoute
  '/_app/live/meetings': typeof AppLiveMeetingsRoute
  '/_app/live/tasks': typeof AppLiveTasksRouteWithChildren
  '/_app/live/tasks/$taskId': typeof AppLiveTasksTaskIdRoute
  '/_app/live/tasks/': typeof AppLiveTasksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/attendance'
    | '/dashboard'
    | '/departments'
    | '/documents'
    | '/employee-add'
    | '/employees'
    | '/expenses'
    | '/leave'
    | '/meetings'
    | '/messages'
    | '/notifications'
    | '/payroll'
    | '/performance'
    | '/profile'
    | '/projects'
    | '/recruitment'
    | '/reports'
    | '/settings'
    | '/task-add'
    | '/tasks'
    | '/employees/$id'
    | '/live/directory'
    | '/live/meetings'
    | '/live/tasks'
    | '/live/tasks/$taskId'
    | '/live/tasks/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/attendance'
    | '/dashboard'
    | '/departments'
    | '/documents'
    | '/employee-add'
    | '/employees'
    | '/expenses'
    | '/leave'
    | '/meetings'
    | '/messages'
    | '/notifications'
    | '/payroll'
    | '/performance'
    | '/profile'
    | '/projects'
    | '/recruitment'
    | '/reports'
    | '/settings'
    | '/task-add'
    | '/tasks'
    | '/'
    | '/employees/$id'
    | '/live/directory'
    | '/live/meetings'
    | '/live/tasks/$taskId'
    | '/live/tasks'
  id:
    | '__root__'
    | '/_app'
    | '/auth'
    | '/_app/attendance'
    | '/_app/dashboard'
    | '/_app/departments'
    | '/_app/documents'
    | '/_app/employee-add'
    | '/_app/employees'
    | '/_app/expenses'
    | '/_app/leave'
    | '/_app/meetings'
    | '/_app/messages'
    | '/_app/notifications'
    | '/_app/payroll'
    | '/_app/performance'
    | '/_app/profile'
    | '/_app/projects'
    | '/_app/recruitment'
    | '/_app/reports'
    | '/_app/settings'
    | '/_app/task-add'
    | '/_app/tasks'
    | '/_app/'
    | '/_app/employees/$id'
    | '/_app/live/directory'
    | '/_app/live/meetings'
    | '/_app/live/tasks'
    | '/_app/live/tasks/$taskId'
    | '/_app/live/tasks/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tasks': {
      id: '/_app/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AppTasksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/task-add': {
      id: '/_app/task-add'
      path: '/task-add'
      fullPath: '/task-add'
      preLoaderRoute: typeof AppTaskAddRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/recruitment': {
      id: '/_app/recruitment'
      path: '/recruitment'
      fullPath: '/recruitment'
      preLoaderRoute: typeof AppRecruitmentRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects': {
      id: '/_app/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AppProjectsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/performance': {
      id: '/_app/performance'
      path: '/performance'
      fullPath: '/performance'
      preLoaderRoute: typeof AppPerformanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/payroll': {
      id: '/_app/payroll'
      path: '/payroll'
      fullPath: '/payroll'
      preLoaderRoute: typeof AppPayrollRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/messages': {
      id: '/_app/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AppMessagesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/meetings': {
      id: '/_app/meetings'
      path: '/meetings'
      fullPath: '/meetings'
      preLoaderRoute: typeof AppMeetingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leave': {
      id: '/_app/leave'
      path: '/leave'
      fullPath: '/leave'
      preLoaderRoute: typeof AppLeaveRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/expenses': {
      id: '/_app/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof AppExpensesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/employees': {
      id: '/_app/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof AppEmployeesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/employee-add': {
      id: '/_app/employee-add'
      path: '/employee-add'
      fullPath: '/employee-add'
      preLoaderRoute: typeof AppEmployeeAddRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/documents': {
      id: '/_app/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AppDocumentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/departments': {
      id: '/_app/departments'
      path: '/departments'
      fullPath: '/departments'
      preLoaderRoute: typeof AppDepartmentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/attendance': {
      id: '/_app/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AppAttendanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/live/tasks': {
      id: '/_app/live/tasks'
      path: '/live/tasks'
      fullPath: '/live/tasks'
      preLoaderRoute: typeof AppLiveTasksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/live/meetings': {
      id: '/_app/live/meetings'
      path: '/live/meetings'
      fullPath: '/live/meetings'
      preLoaderRoute: typeof AppLiveMeetingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/live/directory': {
      id: '/_app/live/directory'
      path: '/live/directory'
      fullPath: '/live/directory'
      preLoaderRoute: typeof AppLiveDirectoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/employees/$id': {
      id: '/_app/employees/$id'
      path: '/$id'
      fullPath: '/employees/$id'
      preLoaderRoute: typeof AppEmployeesIdRouteImport
      parentRoute: typeof AppEmployeesRoute
    }
    '/_app/live/tasks/': {
      id: '/_app/live/tasks/'
      path: '/'
      fullPath: '/live/tasks/'
      preLoaderRoute: typeof AppLiveTasksIndexRouteImport
      parentRoute: typeof AppLiveTasksRoute
    }
    '/_app/live/tasks/$taskId': {
      id: '/_app/live/tasks/$taskId'
      path: '/$taskId'
      fullPath: '/live/tasks/$taskId'
      preLoaderRoute: typeof AppLiveTasksTaskIdRouteImport
      parentRoute: typeof AppLiveTasksRoute
    }
  }
}

interface AppEmployeesRouteChildren {
  AppEmployeesIdRoute: typeof AppEmployeesIdRoute
}

const AppEmployeesRouteChildren: AppEmployeesRouteChildren = {
  AppEmployeesIdRoute: AppEmployeesIdRoute,
}

const AppEmployeesRouteWithChildren = AppEmployeesRoute._addFileChildren(
  AppEmployeesRouteChildren,
)

interface AppLiveTasksRouteChildren {
  AppLiveTasksTaskIdRoute: typeof AppLiveTasksTaskIdRoute
  AppLiveTasksIndexRoute: typeof AppLiveTasksIndexRoute
}

const AppLiveTasksRouteChildren: AppLiveTasksRouteChildren = {
  AppLiveTasksTaskIdRoute: AppLiveTasksTaskIdRoute,
  AppLiveTasksIndexRoute: AppLiveTasksIndexRoute,
}

const AppLiveTasksRouteWithChildren = AppLiveTasksRoute._addFileChildren(
  AppLiveTasksRouteChildren,
)

interface AppRouteChildren {
  AppAttendanceRoute: typeof AppAttendanceRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDepartmentsRoute: typeof AppDepartmentsRoute
  AppDocumentsRoute: typeof AppDocumentsRoute
  AppEmployeeAddRoute: typeof AppEmployeeAddRoute
  AppEmployeesRoute: typeof AppEmployeesRouteWithChildren
  AppExpensesRoute: typeof AppExpensesRoute
  AppLeaveRoute: typeof AppLeaveRoute
  AppMeetingsRoute: typeof AppMeetingsRoute
  AppMessagesRoute: typeof AppMessagesRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppPayrollRoute: typeof AppPayrollRoute
  AppPerformanceRoute: typeof AppPerformanceRoute
  AppProfileRoute: typeof AppProfileRoute
  AppProjectsRoute: typeof AppProjectsRoute
  AppRecruitmentRoute: typeof AppRecruitmentRoute
  AppReportsRoute: typeof AppReportsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTaskAddRoute: typeof AppTaskAddRoute
  AppTasksRoute: typeof AppTasksRoute
  AppIndexRoute: typeof AppIndexRoute
  AppLiveDirectoryRoute: typeof AppLiveDirectoryRoute
  AppLiveMeetingsRoute: typeof AppLiveMeetingsRoute
  AppLiveTasksRoute: typeof AppLiveTasksRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppAttendanceRoute: AppAttendanceRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDepartmentsRoute: AppDepartmentsRoute,
  AppDocumentsRoute: AppDocumentsRoute,
  AppEmployeeAddRoute: AppEmployeeAddRoute,
  AppEmployeesRoute: AppEmployeesRouteWithChildren,
  AppExpensesRoute: AppExpensesRoute,
  AppLeaveRoute: AppLeaveRoute,
  AppMeetingsRoute: AppMeetingsRoute,
  AppMessagesRoute: AppMessagesRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppPayrollRoute: AppPayrollRoute,
  AppPerformanceRoute: AppPerformanceRoute,
  AppProfileRoute: AppProfileRoute,
  AppProjectsRoute: AppProjectsRoute,
  AppRecruitmentRoute: AppRecruitmentRoute,
  AppReportsRoute: AppReportsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTaskAddRoute: AppTaskAddRoute,
  AppTasksRoute: AppTasksRoute,
  AppIndexRoute: AppIndexRoute,
  AppLiveDirectoryRoute: AppLiveDirectoryRoute,
  AppLiveMeetingsRoute: AppLiveMeetingsRoute,
  AppLiveTasksRoute: AppLiveTasksRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
