# Generated by Django 5.2.15 on 2026-07-07 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='working_hours',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
