# Generated by Django 5.2.15 on 2026-07-09 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_task_options_task_completed_at_task_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
