# Generated by Django 5.2.15 on 2026-07-09 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_task_task_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='employee_remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
