# Generated by Django 5.2.15 on 2026-07-09 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_task_employee_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent')], default='PRESENT', max_length=20),
        ),
    ]
